# server:
#   port: 0

# spring:
#   application:
#     name: etudiant-service

#   datasource:
#     url: jdbc:h2:mem:etudiantdb
#     driver-class-name: org.h2.Driver
#     username: sa
#     password:

#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true

#   h2:
#     console:
#       enabled: true

#   security:
#     oauth2:
#       resourceserver:
#         jwt:
#           issuer-uri: http://keycloak:8080/realms/gestion-etudiants

# eureka:
#   client:
#     service-url:
#       defaultZone: http://ms-discovery:8761/eureka


server:
  port: 8081

spring:
  application:
    name: etudiant-service

eureka:
  client:
    service-url:
      defaultZone: http://ms-discover:8761/eureka/
