# server:
#   port: 8761

# spring:
#   application:
#     name: ms-discovery

# eureka:
#   client:
#     register-with-eureka: false
#     fetch-registry: false

# management:
#   endpoints:
#     web:
#       exposure:
#         include: health,info

server:
  port: 8761

spring:
  application:
    name: ms-discover

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
