# server:
#   port: 8080

# spring:
#   application:
#     name: ms-gateway

#   cloud:
#     gateway:
#       discovery:
#         locator:
#           enabled: true
#       routes:
#         - id: etudiant-service
#           uri: lb://etudiant-service
#           predicates:
#             - Path=/api/etudiants/**
#         - id: service-notes
#           uri: lb://service-notes
#           predicates:
#             - Path=/api/notes/**

#   security:
#     oauth2:
#       resourceserver:
#         jwt:
#           issuer-uri: http://keycloak:8080/realms/gestion-etudiants

# eureka:
#   client:
#     service-url:
#       defaultZone: http://ms-discovery:8761/eureka

# management:
#   endpoints:
#     web:
#       exposure:
#         include: health,info

server:
  port: 8080

spring:
  application:
    name: ms-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: enseignants
          uri: lb://service-enseignant
          predicates:
            - Path=/api/teachers/**
          filters:
            - StripPrefix=1

        - id: notes
          uri: lb://service-notes
          predicates:
            - Path=/api/notes/**
          filters:
            - StripPrefix=1

        - id: etudiants
          uri: lb://etudiant-service
          predicates:
            - Path=/api/students/**
          filters:
            - StripPrefix=1

        - id: classes
          uri: lb://service-classe
          predicates:
            - Path=/api/classes/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://ms-discover:8761/eureka/
