server:
  port: 8088

spring:
  application:
    name: ms-gateway

  main:
    web-application-type: reactive

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # ===== AUTHENTICATION (PUBLIC) =====
        - id: auth-login
          uri: lb://service-user
          predicates:
            - Path=/auth/login
          filters:
            - StripPrefix=0

        - id: auth-register
          uri: lb://service-user
          predicates:
            - Path=/auth/register
          filters:
            - StripPrefix=0

        # ===== USER SERVICE (PROTECTED) =====
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/service-user/**
          filters:
            - StripPrefix=1

        # ===== CLASSE =====
        - id: ms-classe
          uri: lb://ms-classe
          predicates:
            - Path=/ms-classe/**
          filters:
            - StripPrefix=1

        # ===== ETUDIANT =====
        - id: ms-etudiant
          uri: lb://ms-etudiant
          predicates:
            - Path=/ms-etudiant/**
          filters:
            - StripPrefix=1

        # ===== NOTE =====
        - id: ms-note
          uri: lb://ms-note
          predicates:
            - Path=/ms-note/**
          filters:
            - StripPrefix=1

        # ===== ENSEIGNANT =====
        - id: ms-enseignant
          uri: lb://ms-enseignant
          predicates:
            - Path=/ms-enseignant/**
          filters:
            - StripPrefix=1

      # ======================
      # CORS GLOBAL
      # ======================
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: 
              - "http://localhost:3000"
              - "http://localhost:5173"
            allowed-headers: "*"
            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allow-credentials: true

      # ======================
      # HTTP CLIENT
      # ======================
      httpclient:
        connect-timeout: 5000
        response-timeout: 10s

# ======================
# ACTUATOR
# ======================
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always

# ======================
# EUREKA
# ======================
eureka:
  instance:
    hostname: ms-gateway
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://ms-discover:8761/eureka
    fetch-registry: true
    register-with-eureka: true

# ======================
# LOGS
# ======================
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.security: DEBUG