# server:
#   port: 0

# spring:
#   application:
#     name: service-enseignant

#   datasource:
#     url: jdbc:h2:mem:enseignantdb
#     driver-class-name: org.h2.Driver
#     username: sa
#     password:

#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true

#   security:
#     oauth2:
#       resourceserver:
#         jwt:
#           issuer-uri: http://keycloak:8080/realms/gestion-etudiants

# eureka:
#   client:
#     service-url:
#       defaultZone: http://ms-discovery:8761/eureka


server:
  port: 8083

spring:
  application:
    name: service-enseignant

  datasource:
    url: jdbc:h2:mem:enseignantdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  client:
    service-url:
      defaultZone: http://ms-discover:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
